# Generated by Django 4.0.4 on 2022-04-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDev',
            new_name='ProjectManager',
        ),
    ]
