# Generated by Django 4.0.4 on 2022-04-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_projectdev_dev_alter_projectdev_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdev',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.project'),
        ),
    ]
