# Generated by Django 4.0.4 on 2022-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_projectdev_projectmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='language',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
