# Generated by Django 4.0.4 on 2022-04-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projectdev_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdev',
            name='dev',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.dev'),
        ),
        migrations.AlterField(
            model_name='projectdev',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.project'),
        ),
    ]
