# Generated by Django 4.0.4 on 2022-04-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_project_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dev',
            field=models.ManyToManyField(related_name='project', to='home.dev'),
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
