# Generated by Django 4.0.4 on 2022-04-21 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_dev_delete_projectmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dev')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
    ]
